### PR TITLE
Issue55

### PR DESCRIPTION
**Pull request by reinholdsson**
Creating this pull request, in case we have ongoing discussion related to this pull request.

### CODE REVIEW

**Comment by reinholdsson** [comment]
Should we print an error or warning when data is missing?

Empty database:

```
db["non-existing"]
NULL
Warning message:
In wrn(17, x$path) :
  the database C:\Users\thorei\AppData\Local\Temp\RtmpQnyhqz\file4d8ebc6823 is empty
```

Missing variable:

```
> db["2x"]
Error in err(6, name) : 2x - file does not exist
```

Perhaps warning is enough?

**Comment by reinholdsson** [comment]
Returning a `vector` vs `data.table` might be a bit confusing, for example when there aren't any dimensions available:

```
db["x", ]  # => vector
db["x", .all]  # => data.table (with one column) (also: db["x", NULL])
```

Is there a huge performance loss of always returning a `data.table`?

Pros: 
- General solution, easier to understand.
- Better looking console output (compare data.table with vector).

Cons:
- Writing conditions using vectors looks better.
- Performance loss.
- Necessary to write `db["x", .all][[1]]` to get the actual vector.

An additional solution is to always return the data as a vector when the query returns a single variable (without several dimensions).

**Comment by mikula** [comment]
This is not about perfomance. 
The common use:
db["birthyear"] or db["sex"] are traditionally used as vectors
We can change it and assume data.table for all output. There is some issue with compatibility of ols scripts nut it's manageable, I suppose

.all as NULL could be a bit confusing when get_variable has different meaning of NULL
We could also define ".all”  as  
-.Machine$integer.max

**Comment by reinholdsson** [comment]
ok, we can discuss which solution that might be preferred. I'm not sure myself :)

I agree on changing `.all` to `-.Machine$integer.max` - if so, I suppose we also need to add some check to disallow for using this number when naming dimensions?

Btw, is the following bug solved in the upcoming commit?

**EDIT**: This seems to work now (not sure why it arised before)

```
db <- cdb(path, read_only = F)
db[] <- data.table(MASS::survey)
db[]
# Error in x$get_variable : $ operator is invalid for atomic vectors
```

Other than that, the tests passes (I have changed `err->wrn` when data is missing).

**Comment by mikula** [comment]
ok list shoud be as.list in cdb-class.r 842

**Comment by mikula** [comment]
Fixed in issue55
data.table as only output
vector or data.table as posible inputs

**Comment by mikula** [comment]
There are still some risks for missunderstandings:
db[] <- data.table(MASS::survey)  # works as expected
db[] <- NULL
but...
db["foo"] <-data.table(MASS::survey)  # picks the first column and store it as variable "foo"
it seems acceptable. The question is if we need a warning here. The effect is somehow hidden
db["foo"] <-data.table(MASS::survey)[,Pulse]  # is a more proper way

**Comment by reinholdsson** [comment]
Looks great!

I agree, a warning would be nice (or perhaps even an error).

I think we should also allow for `data.frame` as input, to make the package simple to use also for small data (and for novices).

```
a[] <- MASS::survey
# Warning message:
# In wrn(22, class(value)) :
#   The 'value' argument in ']<-' should be a vector, data.table, doc or NULL. It is a data.frame .
```

We could just add `if (is.data.frame(x)) x <- as.data.table(x)` (or refactor the code to use `data.frame` compatible syntax).

Using dimensions, there seems to be a minor bug:

```
a[, 2012] <- as.data.table(MASS::survey)
# Error in is.null(name) : 'name' is missing
```

**Comment by mikula** [comment]
data.frame works fine - NOT
db[, 2012] <- MASS::survey
The warning should tell that just the first column was used
I will look into the data.table - problem

**Comment by mikula** [comment]
Better solution:
data.frame or data.table on input => use the column names combined with dhe given dim regardless what i-arg is
issue a warning that name is disregarted

**Comment by reinholdsson** [comment]
The following leads to problems when the column name is `x`:

```
 resOut[,eval(varName):= x$get_variable(name = variable, dims = toRead[k,dims[[1]]], na = na)]
```

since `data.table` think it is a column instead of a `cdb` object. See https://github.com/SwedishPensionsAgency/Coldbir/blob/03b9085c15f29a460e82d376f7cf86758a44f46f/R/cdb-class.r#L783.

I've had the same problem before, and I'll see if I can remember the solution.

**Comment by reinholdsson** [comment]
The issues seems to remain with `data.tables`. To simplify the code a bit (I think we already discussed this), but what do you think about using a character vector instead of `obj$curr_var_tab` when matching/subsetting the choice of variables? Using internal representation such as the generated column names, e.g. `var_2012.12.31`. Some helper functions:

```
to_var_internal_repr <- function(var, dims) {
  paste(var, paste(dims, collapse = "."), sep = ifelse(length(dims) > 0, "_", ""))
}

get_var_internal_repr <- function(x) {
  unlist(strsplit(x, "_"))[[1]]
}

get_dim_internal_repr <- function(x) {
  strsplit(unlist(strsplit(x, "_"))[[2]], "\\.")[[1]]
}
```

Then we convert back and forth and we could also use regexp to match/subset.

**Comment by reinholdsson** [comment]
Some issues:

```
# Don't forget setwd("Coldbir-folder")

library(Coldbir)
library(testthat)

db <- cdb(tempfile(), read_only = F)
x <- data.table(MASS::survey)
setnames(x, c("Wr.Hnd", "NW.Hnd", "Pulse"), c("var", "x", "z"))
db[] <- x
setcolorder(x, sort(names(x)))
db[]

x <- data.table(MASS::survey)
setnames(x, c("Wr.Hnd", "NW.Hnd", "Pulse"), c("var", "x", "z"))
db[, 2010] <- x
setcolorder(x, sort(names(x)))
db[, 2010]

# Run tests
test()  # => Error: get dataset

# Run same code as above again
db <- cdb(tempfile(), read_only = F)
x <- data.table(MASS::survey)
setnames(x, c("Wr.Hnd", "NW.Hnd", "Pulse"), c("var", "x", "z"))
db[] <- x
setcolorder(x, sort(names(x)))
db[]
# Error in `:=`(eval(theVarName), theVariableData) : 
# := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":="). Check is.data.table(DT) is TRUE.

x <- data.table(MASS::survey)
setnames(x, c("Wr.Hnd", "NW.Hnd", "Pulse"), c("var", "x", "z"))
db[, 2010] <- x
# Error in err(11, name) : 
#   Sex - length of variable doesn't match the size of the other columns; nothing will be written

setcolorder(x, sort(names(x)))
db[, 2010]
# Error in `[.data.frame`(x, i) : object 'len' not found
```

It does, however, work when running `make test` in the terminal.

**Comment by reinholdsson** [comment]
`test()` is from package `devtools`. It works fine using `test_package()` directly from the `testthat` package. We will merge this into dev anyway, and the we will start refactoring the code (see issue #76).

**Pull request merged**
